# Generated by Django 2.0 on 2020-07-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_ChatBotDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FruitsID', models.TextField(blank=True, null=True)),
                ('FruitNo', models.IntegerField(blank=True, null=True)),
                ('ImageID', models.IntegerField(blank=True, null=True)),
                ('FruitsTag', models.TextField(blank=True, null=True)),
                ('FruitsName', models.TextField(blank=True, null=True)),
                ('FruitsSize', models.TextField(blank=True, null=True)),
                ('FruitPrice', models.IntegerField()),
                ('Unit', models.TextField(blank=True, null=True)),
                ('FruitDiscount', models.IntegerField()),
                ('FruitBill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FruitNo', models.IntegerField(blank=True, null=True)),
                ('CartItem', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fruits_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FruitsID', models.IntegerField(blank=True, null=True)),
                ('FruitNo', models.IntegerField(blank=True, null=True)),
                ('ImageID', models.IntegerField(blank=True, null=True)),
                ('FruitsTag', models.TextField(blank=True, null=True)),
                ('FruitsName', models.TextField(blank=True, null=True)),
                ('FruitsSize', models.TextField(blank=True, null=True)),
                ('FruitPrice', models.IntegerField()),
                ('Unit', models.TextField(blank=True, null=True)),
                ('FruitDiscount', models.IntegerField()),
                ('FruitBill', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FruitNo', models.IntegerField(blank=True, null=True)),
                ('CartItem', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FruitNo', models.IntegerField(blank=True, null=True)),
                ('fruitName', models.CharField(max_length=100)),
                ('fruitPrice', models.IntegerField()),
                ('Unit', models.TextField(blank=True, null=True)),
                ('FruitsSize', models.TextField(blank=True, null=True)),
                ('fruitQuantity', models.IntegerField()),
                ('fruitDiscount', models.IntegerField()),
                ('fruitBill', models.IntegerField()),
            ],
        ),
    ]
