# Generated by Django 2.0 on 2020-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateGory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FruitNo', models.IntegerField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatDetals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Bot', models.TextField(blank=True, null=True)),
                ('Chat_Time', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
