# Generated by Django 2.0 on 2020-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_chatdetals'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
